### ISSUE TITLE
Dropdown MULTI

### ISSUE THREAD

**Issue by madison13g** [freinric/Cost-of-living_Dashboard#12]
Current dropdown functionality in the dashboard allows for one selection. We want to enable 2+ selections.

**Comment by XiaCatQ** [comment]
Solution:
Add multi = True for 'city' in dcc.Dropdown
Use transform.filter with field = 'city', oneOf = chosen cities in Altair

dcc.Dropdown(
                        id='ycol-widget3',
                        value=['Vancouver', 'Toronto'],  # REQUIRED to show the plot on the first page load
                        options=[{'label': cities, 'value': cities} for cities in data['city']], multi = True)],
                        style={'width': '100%', 'font-family': 'arial', "font-size": "1.1em", 'font-weight': 'bold'}),

@app.callback(
    Output('scatter3', 'srcDoc'),
    Input('xcol-widget3', 'value'),
    Input('ycol-widget3', 'value')
)
def plot_altair3(xcol, ycol):  

    chart = alt.Chart(data).mark_bar().encode(
        x = alt.X(xcol, axis=alt.Axis(format='$', title = None)),
        y = alt.Y('city', axis=alt.Axis(title = None))).transform_filter(alt.FieldOneOfPredicate(field='city', oneOf=ycol)).configure_axis(
    labelFontSize = 16
)

    return chart.to_html()

**Comment by madison13g** [comment]
Solution completed and implemented. Functions as required. Closing issue.
