### ISSUE TITLE
Add: Canada map, map colours to specific prov

### ISSUE THREAD

**Issue by freinric** [freinric/Cost-of-living_Dashboard#52]
So that whenever new choice, the colours stay the same. Right now when change the choice all the colours change.

**Comment by freinric** [comment]
provdict = {'AB': 'Alberta', 
            'BC':'British Columbia', 
            'SK':'Saskatchewan',
            'MB':'Manitoba',
            'Maritimes':['New Brunswick','Newfoundland and Labrador','Nova Scotia','Prince Edward Island'],
            'Territories':['Northwest Territories','Nunavut','Yukon'],
            'ON':'Ontario',
            'QB':'Quebec'}

**Comment by XiaCatQ** [comment]
appoint colors to each province now.
